### ISSUE TITLE
I have a question, what is the difference between  require('./typescript/lib/tsc.js'); and require('typescript/lib/tsc.js')

### ISSUE THREAD

**Issue by lovetingyuan** [johnsoncodehk/vue-tsc#10]
what is the difference between  require('./typescript/lib/tsc.js'); and require('typescript/lib/tsc.js')?

**Comment by lovetingyuan** [comment]
except you can specify the exact version of typescript

**Comment by johnsoncodehk** [comment]
`require('./typescript/lib/tsc.js')` is a hack version `tsc`, added proxy code to support `*.vue` files: 
https://github.com/johnsoncodehk/vue-tsc/blob/5b5f879d6f38472138f45d64e309324ab7f558d6/clone-typescript.js#L22

Yes I plan to support specify typescript version if possible, this is library is still in preview status, please wait.

**Comment by lovetingyuan** [comment]
oh I see, thank you very much😊

**Comment by johnsoncodehk** [comment]
> except you can specify the exact version of typescript

Supported in 0.2.0.
