### ISSUE TITLE
vue-tsc failing on '@update:var' handlers 

### ISSUE THREAD

**Issue by ValdoGhafoor** [johnsoncodehk/vue-tsc#11]
Hi,
Using a fresh vue-ts Vite template and adding an event handler using '@update:varName' syntax raises an error on vue-tsc command.

`@update:var="() => {}"`

gives

`Property 'var' does not exist on type '{ msg: { type: StringConstructor; required: boolean; }; }'.`
Even if event is declared in component emits

**Comment by johnsoncodehk** [comment]
Duplicate of #12
