### ISSUE TITLE
vue-tsc failing on '@update:var' syntax event handlers

### ISSUE THREAD

**Issue by ValdoGhafoor** [johnsoncodehk/vue-tsc#12]
Hi,
Using a fresh vue-ts Vite template and adding an event handler using '@update:varName' syntax raises an error on vue-tsc command.

`@update:varName="() => {}"
`
gives

`Property 'varName' does not exist on type ...etc`

Even if event update:varName and prop varName are declared in component

Sorry for duplicate issue, got a bug with github

**Comment by johnsoncodehk** [comment]
You need to define `varName` in component props: `props: { varName: ... }`

**Comment by ValdoGhafoor** [comment]
Got it, thanks.
prop was there but not with the same casing.

I feel like this should be in the doc if it's not already.
