### ISSUE TITLE
Dynamic Slot doesn't pass vue-tsc --noEmit Commands

### ISSUE THREAD

**Issue by yng88** [johnsoncodehk/vue-tsc#13]
```
<template>
<tbody>
      <tr
        v-for="item in items"
      >
        <td
          v-for="(val, i) in item"
          :key="i"
        >
          <slot
            :name="i"
            :[i]="val"
          >
            {{ val }}
          </slot>
        </td>
        <td><slot name="actions" /></td>
      </tr>
    </tbody>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  props: {
    headers: { type: Array },
    items: Array,
  },
  setup() {},
})
</script>
```
When I make the component,  following error occured .

```
Property 'status' does not exist on type '{ actions: {}; }'.

    <template #status="item">
```
this is use case

```
<template #status="item">
        {{ item.status }}
    </template>
```
I want to know how to resolve these probrem.

**Comment by johnsoncodehk** [comment]
Try this:

```vue
<template>
  <tbody>
    <tr v-for="item in items">
      <td v-for="(val, i) in item" :key="i">
        <slot :name="i" v-bind="item">{{ val }}</slot>
      </td>
      <td>
        <slot name="actions" />
      </td>
    </tr>
  </tbody>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
export default defineComponent({
  props: {
    headers: { type: Array },
    items: Array as PropType<Record<'status' | 'others', any>[]>,
  },
  setup() { },
})
</script>
```

**Comment by yng88** [comment]
Thank you for your awesome answer.
Since the key of the object in the array given to item is changed dynamically, the notation Record <'status' |'others', any> [] can only support a finite number of patterns.
The props called item are dynamically retyped.
In this case, how should we solve it?

**Comment by johnsoncodehk** [comment]
@yng88 please try this in volar 0.23.7, if it working I will update `vue-tsc`:

```ts
items: Array as PropType<Record<string, any>[]>,
```

**Comment by cool-delete** [comment]
![image](https://user-images.githubusercontent.com/13638610/115960385-aedc5800-a543-11eb-9fc6-da117b0bf91b.png)
interface car {
    identificationCode: "",
          superiorDepartments: "",
          higherUnit: "",
          state: "",
          trackPoints:[{
                lng: number,
                lat: number,
              }],
          position: {
            lng: number,
            lat: number,
            icar: {},
          },
        }
There is no intelligent inference after writing

Can tsc not check template syntax?
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
@cool-delete vue-tsc is use for pipeline, please use [Volar](https://github.com/johnsoncodehk/volar) for IDE.
