### ISSUE TITLE
incremental mode is not yet support

### ISSUE THREAD

**Issue by anncwb** [johnsoncodehk/vue-tsc#15]
Run vue-tsc in my project --noEmit will report this error

![image](https://user-images.githubusercontent.com/28132598/114401527-95e3b680-9bd5-11eb-8bb5-2b2d9a9bbc87.png)

**Comment by johnsoncodehk** [comment]
If your project is not monorepo, make sure `composite` and `declaration` options is not enable in tsconfig.json.

**Comment by anncwb** [comment]
I did not configure this
![image](https://user-images.githubusercontent.com/28132598/114492644-8acb6d80-9c4b-11eb-8a2c-b0f2896b518c.png)

**Comment by johnsoncodehk** [comment]
@anncwb sorry, and also should not enable `incremental` option. 😅

**Comment by anncwb** [comment]
Thanks, it works fine
