### ISSUE TITLE
Why verify node_modules

### ISSUE THREAD

**Issue by anncwb** [johnsoncodehk/vue-tsc#16]
In order to execute vue-tsc --noEmit, the following error occurred, can I ignore the verification of node_modules

![image](https://user-images.githubusercontent.com/28132598/114494114-54dbb880-9c4e-11eb-868c-b478675f6186.png)

**Comment by johnsoncodehk** [comment]
Try this `vue-tsc --noEmit --skipLibCheck`.

**Comment by anncwb** [comment]
The same output

**Comment by johnsoncodehk** [comment]
Is `tsc --noEmit --skipLibCheck` (not vue-tsc) has same output?

**Comment by Zhaocl1997** [comment]
I got this error executing `vue-tsc --noEmit --skipLibCheck`

![微信截图_20210413133637](https://user-images.githubusercontent.com/52120824/114502176-f0c0f080-9c5d-11eb-83df-b569c3b17f0d.png)

**Comment by Zhaocl1997** [comment]
I got this error executing `vue-tsc --noEmit --skipLibCheck`

![微信截图_20210413133637](https://user-images.githubusercontent.com/52120824/114502176-f0c0f080-9c5d-11eb-83df-b569c3b17f0d.png)

**Comment by johnsoncodehk** [comment]
@Zhaocl1997 see https://github.com/johnsoncodehk/vue-tsc/issues/15.
