### ISSUE TITLE
Not in sync with Volar

### ISSUE THREAD

**Issue by zigomir** [johnsoncodehk/vue-tsc#17]
Hi,

I started getting `error TS7006: Parameter 'value' implicitly has an 'any' type.` for type checks inside `template` tags from `vue-tsc`, whereas `volar` in VSCode isn't reporting this error and hovering over value prints correct type

### Volar:

<img width="550" alt="Screenshot 2021-04-13 at 15 59 51" src="https://user-images.githubusercontent.com/957321/114565162-4f439a00-9c71-11eb-94cc-4c376c765098.png">

### vue-tsc:

<img width="853" alt="Screenshot 2021-04-13 at 16 00 35" src="https://user-images.githubusercontent.com/957321/114565277-684c4b00-9c71-11eb-8fd6-a2d78e68f041.png">

Does this mean `vue-tsc` is behind `volar` versions?

**Comment by johnsoncodehk** [comment]
Thanks for you report! It's seem a bug in 0.0.23 (this version is fix pug checking only), please downgrade to 0.0.22 for now if you're not using pug.

**Comment by zigomir** [comment]
Thanks – this fixes it 👍

**Comment by johnsoncodehk** [comment]
Fixed in 0.0.24, and 0.0.23 has been deprecated, because there has some serious typecheck mistake...
