### ISSUE TITLE
How to allow custom css props like :style="{'--offset-x': someVar }"

### ISSUE THREAD

**Issue by jjdive** [johnsoncodehk/vue-tsc#19]
Hi!

Thanks in advance for any help on this. I'm getting this error when trying to pass custom CSS properties from template. I wonder if there is a "correct" way to augment this particular type to accept them. Just recently learning TS.

```
Type '{ '--offset-x': number; }' is not assignable to type 'StyleValue | undefined'.
  Object literal may only specify known properties, and ''--offset-x'' does not exist in type 'CSSProperties | StyleValue[]'.
```

**Comment by johnsoncodehk** [comment]
Try this.

```
:style="
  // @ts-ignore
  {'--offset-x': someVar }
"
```

**Comment by johnsoncodehk** [comment]
Sorry I did not see you required a way to augment particular type, you can also try:

```ts
declare module '@vue/runtime-dom' {
  export interface CSSProperties {
    '--offset-x': string
  }
}
```

**Comment by jjdive** [comment]
Thanks @johnsoncodehk !

I checked https://github.com/johnsoncodehk/volar/issues/30 and tried the snippet you suggested there. Not passing the style object inline and passing and object reference, whether from data, ref() or even an inlined method (useful in combination with a v-for), seems to bypass the check of the CSSProperties type.

Though this solves my issue, I don't know if that's the intended behavior, so i'm letting you know.

Thank you very much!

**Comment by johnsoncodehk** [comment]
@jjdive You are welcome, and please pay attention to my last comment. 😅

**Comment by jjdive** [comment]
@johnsoncodehk, i saw it right after sending my last message :sweat_smile:. Thinkering with that since then i got another error, but eventually managed to see that the augment needs the new prop key to be optional so other styles don't expect it to be required. So it should be:

```ts
declare module '@vue/runtime-dom' {
  export interface CSSProperties {
    '--offset-x'?: string
    ... any other custom css properties one might need across the app 
  }
}
```

It's now working and it even let me know that i was passing a number instead of a string in another component (units are needed for the transform to work properly down the line), awesome! :partying_face:.

Thank you so very much!
