### ISSUE TITLE
Passing a setup function to defineComponent() throws error if the template has slots

### ISSUE THREAD

**Issue by jjdive** [johnsoncodehk/vue-tsc#21]
For a component declared in a SFC like so:

```ts
export default defineComponent(function ComponentName(){
  // contents that would otherwise be in the setup() function
})
```

... if the corresponding template has a `<slot />`, the compiler will throw:

```
[corresponding .vue file] - error TS2322: Type '{}' is not assignable to type 'never'.

#       <slot />
         ~~~~
```

The error will be slightly different if you try to pass attributes to the slot (scoped slot).

Is this expected behavior? Didn't see anything about it in https://v3.vuejs.org/api/global-api.html#definecomponent.

**Comment by johnsoncodehk** [comment]
Fixed in 0.0.25, thanks for your report!
