### ISSUE TITLE
Incorrect type checking when destructuring dynamic slots

### ISSUE THREAD

**Issue by Lennart93** [johnsoncodehk/vue-tsc#22]
I have a generic Table component that contains two properties:

### Table.vue
```
props: {
    headers: {
      type: Array as PropType<{ value: string; text: string }[]>,
      required: true,
    },
    items: {
      type: Array as PropType<Record<string, any>[]>,
      required: true,
    }
  },
```

In the template I have a dynamic named item slot which bind the header and the item to the slot:
```
 <td>
      <slot :name="`item[${header.value}]`" :header="header" :item="item">
           {{ item[header.value] }}
      </slot>
</td>
```

### Parent.vue
I make use of the slot in the parent component:
```
    <Table :headers="headers" :items="items">
      <template #item[id]="{ item }">{{ numFormat(item) }}</template>
    </Table>
```

When type checking the build **the following error message** is displayed:
```
- error TS2339: Property 'item' does not exist on type '{ name: string; header: { value: string; text: string; }; } | { name: string; header: { value: string; text: string; }; item: Record<string, any>; }'.

16       <template #item[id]="{ item }">{{ numFormat(item) }}</template>
                                ~~~~


```

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide a reproduce project, you can modify https://github.com/johnsoncodehk/volar-starter.

**Comment by Lennart93** [comment]
@johnsoncodehk Thanks for your quick reply.  I couldn't also reproduce the issue on the provided template, so I investigated my branch further.

This problem relies in versions `< 0.0.21`. Upgrading to version 0.0.22 or higher solves the issue. My apologies for not trying this sooner! [Reproduce project](https://github.com/Lennart93/vue-tsc-dynamic-slots)
