### ISSUE TITLE
How to define this.$emit

### ISSUE THREAD

**Issue by cool-delete** [johnsoncodehk/vue-tsc#24]
![image](https://user-images.githubusercontent.com/13638610/115961194-e1884f80-a547-11eb-96fd-91aee63ebb92.png)
![image](https://user-images.githubusercontent.com/13638610/115961200-ef3dd500-a547-11eb-8ea7-17b95c64a21b.png)

**Comment by johnsoncodehk** [comment]
You should wrap you component by `defineComponent()`.

**Comment by cool-delete** [comment]
thx
