### ISSUE TITLE
How to define the objects mounted by app.config.globalProperties

### ISSUE THREAD

**Issue by cool-delete** [johnsoncodehk/vue-tsc#26]
![image](https://user-images.githubusercontent.com/13638610/116454616-c5134c80-a892-11eb-94a2-7a402afcab9c.png)

export const http = axios.create({
  baseURL: 'http://localhost:4000',
  timeout: 10000,
  // headers:{"X-Requested-With":"XMLHttpRequest"},
  withCredentials: false

})
export default {
  http,
  install(app: App) {
    app.config.globalProperties.$http = http
  }
}

**Comment by cool-delete** [comment]
![image](https://user-images.githubusercontent.com/13638610/116463336-29d3a480-a89d-11eb-8c1a-6ec58972ccaa.png)
Can't vue customize the type in the prop? But after the definition
Will get error
`Right-hand side of 'instanceof' is not callable`

**Comment by johnsoncodehk** [comment]
Use provide / inject, see: https://v3.vuejs.org/guide/composition-api-provide-inject.html

Please ask TS version to [Vue Discord](https://discord.com/channels/325477692906536972/331999220125138944).
