### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Ancient-Dragon** [johnsoncodehk/vue-tsc#27]
Please can you add a license to your repo and package.json?

Thanks.

**Comment by Ancient-Dragon** [comment]
@johnsoncodehk sorry to be a pain but could you add the license type to package.json that way it’ll be part of the packages metadata

**Comment by johnsoncodehk** [comment]
Sorry I'm not sure, does this right?

https://github.com/johnsoncodehk/vue-tsc/blob/230d1e24922f459a0b55c8341c716c7cfe61903c/package.json#L4

Btw just curious, will there be any restrictions on you without a license?

**Comment by Ancient-Dragon** [comment]
Perfect thank you! Yes, the company I work for blocked the package because it didn’t have a licence. So once you push this I’ll be able to use it. Thanks for doing both of those, if you can let me know when you do the next release that would be great!

**Comment by johnsoncodehk** [comment]
Published to 0.1.2. :)
