### ISSUE TITLE
`vue-tsc` v0.1.0 has vulnerabilities

### ISSUE THREAD

**Issue by cawa-93** [johnsoncodehk/vue-tsc#28]
```node
# npm audit report

yargs-parser  <=13.1.1 || 14.0.0 - 15.0.0 || 16.0.0 - 18.1.1
Prototype Pollution - https://npmjs.com/advisories/1500
fix available via `npm audit fix --force`
Will install vue-tsc@0.0.26, which is a breaking change
node_modules/yargs-parser
  meow  5.0.0 - 6.0.1
  Depends on vulnerable versions of yargs-parser
  node_modules/meow
    @starptech/prettyhtml  *
    Depends on vulnerable versions of meow
    node_modules/@starptech/prettyhtml
      vscode-vue-languageservice  *
      Depends on vulnerable versions of @starptech/prettyhtml
      node_modules/vscode-vue-languageservice
        vue-tsc  >=0.1.0
        Depends on vulnerable versions of vscode-vue-languageservice
        node_modules/vue-tsc
```

**Comment by johnsoncodehk** [comment]
0.0.26 has same dependencies, but 0.0.26 use built-in node_modules so npm does not report...

I will split dependencies by Plugin API refactor, but this is not easy to start, see: https://github.com/johnsoncodehk/volar/discussions/168

**Comment by cawa-93** [comment]
It seems to me to give up a package `@starptech/prettyhtml` in favor of an alternative if such exists. This package has not been updated for 2 years and all the tree of dependencies under it is a bit obsolete.

**Comment by johnsoncodehk** [comment]
@cawa-93 I tried Prettier, but... prettyhtml is much better.

I actually want to [make a new one](https://github.com/johnsoncodehk/volar/projects/1#card-58150014), but I will not promise because here already lot of work. :/
