### ISSUE TITLE
Emits prioritizing the wrong type

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/vue-tsc#33]
Related issue: johnsoncodehk/volar#188

For some reason I can't rollback to previous version that had no errors. Are you sure your deploy process doesn't break anything? (maybe I'm just ignorant. I reverted package-lock to previous version and it worked)

**Comment by johnsoncodehk** [comment]
Fixed `vscode-vue-languageservice` after version in 0.1.3.
