### ISSUE TITLE
Operator '+' cannot be applied to types 'string | number | symbol' and 'number'.

### ISSUE THREAD

**Issue by gd4Ark** [johnsoncodehk/vue-tsc#36]
template:
```html
<el-menu-item v-for="(developer, index) in developers"
              :key="developer.id"
              :index="index + 1"
              @click="onActive(developer)">
  <template #title>
    {{ developer.name }}
  </template>
</el-menu-item>
```
error:
```bash
Operator '+' cannot be applied to types 'string | number | symbol' and 'number'.
```

**Comment by johnsoncodehk** [comment]
Make sure `developers` is not any type, otherwise index is `string | number | symbol` type in expected.

**Comment by johnsoncodehk** [comment]
You can use `@ts-ignore` in template expression. Currently not support ignore type-checking for `<template>`, you can open feature request to [Volar](https://github.com/johnsoncodehk/volar/issues) for discuss if you want.
