### ISSUE TITLE
运行vue-tsc --noEmit命令无任何反应

### ISSUE THREAD

**Issue by a15965734368** [johnsoncodehk/vue-tsc#37]
### 问题描述
我是从vite 1.x升级至2.3.4之后出现的问题，运行 `npm run build` 时无任何反应，经过排查发现是 `vue-tsc --noEmit`的问题，运行命令后会一直卡在这个命令上，但是观察CPU运行情况，它实际是在运行的，我怀疑是进入了长循环。我的项目JS文件是全部用ts写的，但是.vue文件并没有。目前项目文件并没有多少，可以排除是因为项目太大导致的问题。我本地开发了个npm包，我用`npm link project-name`链接导入的，会不会和这个有关系？

### 解决问题
像这种问题，仅仅通过我的描述很难去定位问题，我想知道我能否自己手动排除出问题，如果可以，我应该怎么做？

### 运行环境
```node
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 7.51 GB / 15.42 GB
  Binaries:
    Node: 14.7.0 - D:\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - D:\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.72
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
  Node version: 14.7.0
  Typescript version: 4.1.3
```

**Comment by johnsoncodehk** [comment]
Can this problem reproduce from `tsc --noEmit` with TS 4.2.4?

**Comment by johnsoncodehk** [comment]
Try `vue-tsc@0.1.7`.
