### ISSUE TITLE
Only validate files with lang="ts"

### ISSUE THREAD

**Issue by NikhilVerma** [johnsoncodehk/vue-tsc#42]
Currently vue-tsc seems to validate all `vue` files regardless if they use Typescript or not. If a project is adopting Typescript it  makes it difficult to use vue-tsc.

**Comment by johnsoncodehk** [comment]
You could config `"allowJs": false` in tsconfig to ignore `<script lang="js">`.

**Comment by NikhilVerma** [comment]
@johnsoncodehk  What you are referring to is the `checkJs` flag. `allowJs` flag simply allows TS to scan JS files, not validate them. I believe this issue is still relevant.
