### ISSUE TITLE
Vulnerabilities on `trim-newlines` and `yargs-parser`

### ISSUE THREAD

**Issue by zyrouge** [johnsoncodehk/vue-tsc#44]
![image](https://user-images.githubusercontent.com/50770114/123964018-a9cad780-d9d0-11eb-8933-efbb3288df3a.png)
![image](https://user-images.githubusercontent.com/50770114/123964041-afc0b880-d9d0-11eb-877e-652d46efac4f.png)

**Comment by LeoniePhiline** [comment]
Thank you! 🙏
