### ISSUE TITLE
校验的类型与用户定义的 ts 类型不一致

### ISSUE THREAD

**Issue by mrxu0** [johnsoncodehk/vue-tsc#47]
发生问题的错误：
`
src/pages/login/Login.vue:6:62 - error TS2322: Type '(values: FormState) => void' is not assignable to type '(...payload: unknown[]) => unknown'.
  Types of parameters 'values' and 'payload' are incompatible.
    Type 'unknown' is not assignable to type 'FormState'.

                     <Form :model="formState" :rules="rules" @finish="onSubmit" ref="formRef">
`
用户的定义：
`
onFinish: (...args: any[]) => any;
`

是使用了 antdv  的 form 组件发生的

**Comment by johnsoncodehk** [comment]
Please ask to [Vue Discord](https://discord.com/channels/325477692906536972/331999220125138944). See https://github.com/johnsoncodehk/vue-tsc#navigation.
