### ISSUE TITLE
Error on radio input

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/vue-tsc#55]
vue-tsc version: 0.2.2

I have this input (radio reference: https://v3.vuejs.org/guide/forms.html#radio):
```
  <input
      :id="option[valueField]"
      v-model="inner"
      class="radio"
      type="radio"
      :disabled="disabled"
      :name="name"
      :value="option[valueField]"
  />
```

But running `vue-tsc` gives me this error:

![Снимок экрана 2021-08-10 в 11 24 57](https://user-images.githubusercontent.com/16173870/128833910-b79404fb-f88b-4c0a-ac60-164d1625f746.png)

Volar doesn't give me this error. I guess it thinks `value` from `v-model` conflicts with `value`?

If I remove `:value="option[valueField]"` component breaks.

**Comment by Shinigami92** [comment]
I had this issue too and solved it by (in your case) set the correct default for `inner`

So I assume you have e.g. 

```ts
const inner = ref(option[valueField])

// Or lazy init

const inner = ref()
// vvv Or somewhere else
onBeforeMount(() => {
  inner.value = option[valueField]
})
```

**Comment by sheremet-va** [comment]
My `inner` is `computed` for `props.modelValue` that emits `update` (like `useVModel` in `vueuse`)

But thanks for your help, I will try to bypass this error.
