### ISSUE TITLE
checkbox input doesn't work with boolean value

### ISSUE THREAD

**Issue by boonyasukd** [johnsoncodehk/vue-tsc#56]
Hi,
I tried to upgrade an existing typescript project to `vite` and `vue@3.2.1` (which uses `vue-tsc@0.2.2`). The code seems to run just fine in `dev` mode, but it fails during `build`.

![image](https://user-images.githubusercontent.com/8109816/128962462-80ed4e40-ca3a-494f-bb91-ae356244cb11.png)

Also, in VSCode, after commenting/uncommenting the offending line a couple of times, `volar` just suddenly marked the line in red with the following error (it didn't mark the line like this before):

![image](https://user-images.githubusercontent.com/8109816/128962552-d543789f-c15b-499a-a9ad-6b32588a9ed1.png)

I tried to create a smaller reproduction project, but the error doesn't appear. Unfortunately this bug only happens to a private project which I cannot readily share. :-/

As a workaround, I disable `vue-tsc` from `npm run build` for the time being.

**Comment by johnsoncodehk** [comment]
Please check the version of `node_modules/vscode-vue-languageservice/package.json`, if it's not 0.26.15, try delete yarn.lock / package-lock.json and install node_modules again to update `vscode-vue-languageservice`.
