### ISSUE TITLE
TS2322 when using a boolean value for a radio button

### ISSUE THREAD

**Issue by antony-k1208** [johnsoncodehk/vue-tsc#58]
Hi,

when using a radio button with a boolean value, there is an error reported. See the following image:

![image](https://user-images.githubusercontent.com/4183726/129035342-0365e0e2-d38d-4a18-9800-8092eab4e86e.png)

I tried to change it to a numeric value with 0 and 1, but then v-model gets underlined with the same message I reported earlier #57.

![image](https://user-images.githubusercontent.com/4183726/129035626-096881b9-108c-4ad7-a70e-571538db50e4.png)

Again thank you very much!

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/vue-tsc/issues/57#issuecomment-897276138.

- `0 | 1` can't assign to `Booleanish`: https://github.com/vuejs/vue-next/blob/7ffa225aa334f0fd7da6ba30bee9109de3597643/packages/runtime-dom/types/jsx.d.ts#L458
- `true` can't assign to `string | string[] | number`: https://github.com/vuejs/vue-next/blob/7ffa225aa334f0fd7da6ba30bee9109de3597643/packages/runtime-dom/types/jsx.d.ts#L483
