### ISSUE TITLE
v-for | variable is declared but its value is never read | ts(6133)

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/vue-tsc#59]
I have a v-for where I don't need the variable but the index.

How can I workaround that? Something like using underscore to suppress the error doesn't work 🙁 

![image](https://user-images.githubusercontent.com/7195563/129330464-586949ad-ab66-466d-a713-eab9321ca314.png)

```pug
//- ...
v-col(cols="12", v-for="(line, index) in customText.lines1", :key="`l1-${index}`")
  //-                    ~~~~ 'line' is declared but its value is never read.ts(6133)
  v-text-field(
    v-model="customText.lines1[index]"
  )
  //- ...
```

**Comment by johnsoncodehk** [comment]
Blocking by upstream, see https://github.com/johnsoncodehk/volar/issues/329.

**Comment by Shinigami92** [comment]
My workaround for now:

```ts
:_ignoreLine="line",
```

🤣
