### ISSUE TITLE
v-if | null check doesn't work for events (?)

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/vue-tsc#60]
It seems that `v-if` is not forwarded for event bindings 🤔 
But bindings like `v-text` works

```ts
const variable: Ref<Something | null>
const doSomething(x: Something)
```

```pug
button(v-if="variable", v-text="variable.text", @click="doSomething(variable)")
//-                                                                 ~~~~~~~~ cannot be null
```

![image](https://user-images.githubusercontent.com/7195563/129340390-75367e04-bc05-42d3-a8d4-a7c19baf65dc.png)

**Comment by johnsoncodehk** [comment]
This is expected, see https://github.com/johnsoncodehk/volar/discussions/146.

**Comment by Shinigami92** [comment]
Okay, so I need to wait on https://github.com/vuejs/vue-next/issues/1359
And just use workarounds for this at the moment, okay

Thanks for the incredible fast answer 🚀

**Comment by Shinigami92** [comment]
My workaround is now:

```pug
@click="template && openSharedComponentDialog(template.sharedPath)"
```
