### ISSUE TITLE
How does vue-tsc skip node_modules?

### ISSUE THREAD

**Issue by 1018715564** [johnsoncodehk/vue-tsc#62]
I am using husky+lint-stage, please tell me how vue-tsc can better integrate into this technology stack, thank you

**Comment by johnsoncodehk** [comment]
Please use `--skipLibCheck` flag, see #52, #16.

**Comment by 1018715564** [comment]
> 请使用`--skipLibCheck`标志，参见#52 , #16。

Can this library use lint-stage and only check the files in the temporary storage area?

**Comment by johnsoncodehk** [comment]
Sorry I have no experience with lint-stage. vue-tsc is just a wrapper of typescript tsc, please ask for typescript community for this problem.

**Comment by 1018715564** [comment]
> Sorry I have no experience with lint-stage. vue-tsc is just a wrapper of typescript tsc, please ask for typescript community for this problem.

all right, thank you,have a good day~
