### ISSUE TITLE
Lint error when binding v-model to nullable value

### ISSUE THREAD

**Issue by KrakerXyz** [johnsoncodehk/vue-tsc#63]
This might be by design so I totally accept that as an answer, but wanted to open an just in case it's something you could tweak to accept as valid.

When we declare a a property such as 

```typescript
interface Building {
   construction?: string | null
}
```

and we try to bind construction using v-model such as
```typescript
<select
   class="form-select"
   v-model="dirtyBuilding.construction"
>
   <option>...</option>
</select>
```

This works completely fine at runtime but we get the following from vue-tsc

![image](https://user-images.githubusercontent.com/3339029/130069827-d27ae49d-ce5a-4397-b3b4-a19982c69783.png)

Please let me know if there any additional detail you'd like me to provide.

**Comment by johnsoncodehk** [comment]
This is correct TS behavior, please try replace `construction?: string | null` to `construction?: string`.

**Comment by KrakerXyz** [comment]
Yeah,, if only it were that simple. For better or worse, the API design has requirements for null values so we need to leave it as-is. 

I'll write a typescript generic type that will convert the type to one that removes null from unions. Thanks for the quick response.
