### ISSUE TITLE
Thousands of TS errors

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/vue-tsc#65]
My companies project uses vue-tsc `~0.3.0` and vscode-vue-languageservice `~0.27.7`
Last week everything worked, but today (after weekend) I just run `rm yarn.lock && yarn` to update all dependencies and now when I run `yarn vue-tsc --noEmit` I get `3780` TS errors.

They mostly look like `TS2304: Cannot find name 'XXX'.` or `TS2306: File 'XXX' is not a module.`

But even when I pin the both deps, I still get these errors.
Only when I reset my `yarn.lock` and `package.json` and then run `yarn install --immutable` then I don't get the errors.

But this or that way, vite dev server shows everything works normally.

**Comment by Shinigami92** [comment]
See https://github.com/johnsoncodehk/volar/discussions/437 🤔 
Could be related

**Comment by johnsoncodehk** [comment]
Replied, reproduce wanted. :S

**Comment by Shinigami92** [comment]
Repro: https://github.com/Shinigami92/repro-vue-tsc-65/commits/master

**Comment by Shinigami92** [comment]
The second error occurred through `tsconfig.json` setting `noUnusedLocals` to `true`

Setting it to `false`, I'm down to `327` errors.
Could you fix that? I would like to stay on `"noUnusedLocals": true`

... Will dig further down for the other errors ...

**Comment by johnsoncodehk** [comment]
> Could you fix that? I would like to stay on `"noUnusedLocals": true`

I think this is correct report, if you have no use `{ on }`.

**Comment by Shinigami92** [comment]
> I think this is correct report, if you have no use `{ on }`.

But I have... that's the point ^^, otherwise I would remove it

---

The other errors are really random and I currently don't find out why the occur 🤔 

I will update the repro now, but everything in it works...

**Comment by Shinigami92** [comment]
Also before last thursday I didn't had all these issues, then some updates in `volar` and `vue`/`vscode` language server and `vue-tsc` happend, and after that it broke.
But I also cannot pin versions or so. When I just update something and recreate the `yarn.lock` after that it's broken.

**Comment by johnsoncodehk** [comment]
I only see the declared but never read problem.

![image](https://user-images.githubusercontent.com/16279759/131694456-d5fef9e9-6679-4b55-bb3b-0dd2fd1a5adf.png)
![image](https://user-images.githubusercontent.com/16279759/131694647-cd3e94f6-79e3-4de3-bfe1-54d39a72aa50.png)

**Comment by johnsoncodehk** [comment]
It's because line 7 `v-on="{ ...tooltip, ...menu }"` don't have event name, so volar ignore this expression. What is the nameless event behavior?

**Comment by Shinigami92** [comment]
I have one more step to success! I found out that the issue that all these variables cannot be found is based on one sub-sub component!
This component uses some really special stuff, but seems to _crash_ the parser and therefore cannot be compiled leading to un-compiled code for the components using it traversing up the tree to the root views.
All views/components that has not this component in use anywhere are working just fine.

Now I need to find out what exactly the problem is.

**Comment by Shinigami92** [comment]
It has something to do with following code

```pug
v-btn(icon, @click="currentPreviewIndex--", :disabled="currentPreviewIndex <= 0")
//-                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^~~~
```

But even when I try to reproduce it, it just works
I'm so confused

It took me 2-3 hours to find me this code line

I think my workaround would be for now to move this condition to a computed and then use that

**Comment by johnsoncodehk** [comment]
It seem a pug parser problem, and working good in html. Will check it.

**Comment by johnsoncodehk** [comment]
We use HTMLDocument from `vscode-html-languageservice` to parse SFC, it detected `<=` is a html start tag, so all behind SFC blocks is broken. Don't know how to handle yet. :S

**Comment by johnsoncodehk** [comment]
Please track https://github.com/johnsoncodehk/volar/issues/451.
