### ISSUE TITLE
Install as devDependency?

### ISSUE THREAD

**Issue by JsonKody** [johnsoncodehk/vue-tsc#73]
## Isn't vue-tsc a "devDependency"?

On [NPM page](https://www.npmjs.com/package/vue-tsc) the installation is: 
```npm i vue-tsc```

Shoudn't it be:
```npm i -D vue-tsc``` ?

Because I just installed it to "dependencies" and it doesn't look good.

**Comment by Shinigami92** [comment]
But how is it possible to change this?

**Comment by johnsoncodehk** [comment]
Why are very upstream issues appearing in this gadget 😂, please forward to https://github.com/npm/feedback/discussions.
